#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := touch_sense_sensitivity_detect

include $(IDF_PATH)/make/project.mk
